### 3.1
GET http://localhost:3001/api/persons

### 3.2
GET http://localhost:3001/info

### 3.3
GET http://localhost:3001/api/persons/1

### 3.3
GET http://localhost:3001/api/persons/21

### 3.4
DELETE http://localhost:3001/api/persons/4

### 3.4
GET http://localhost:3001/api/persons

### 3.5
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "YY",
  "number": "123-456789"
}

### 3.5
GET http://localhost:3001/api/persons

### 3.6
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "YMHMZY"
}

### 3.6
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Arto Hellas",
  "number": "123-456789"
}

### 3.10
GET https://fullstack-submission-qoz8.onrender.com/api/persons

### 3.10
GET https://fullstack-submission-qoz8.onrender.com/api/persons/1

### 3.10
POST https://fullstack-submission-qoz8.onrender.com/api/persons
content-type: application/json

{
  "name": "LZY",
  "number": "123"
}

### 3.10
GET https://fullstack-submission-qoz8.onrender.com/api/persons

### 3.10
DELETE https://fullstack-submission-qoz8.onrender.com/api/persons/3

### 3.10
GET https://fullstack-submission-qoz8.onrender.com/api/persons
